repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        files: ^sarif/