name: Build

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - azure-pipelines/release.yml

pr:
  branches:
    include:
      - main
  paths:
    exclude:
      - azure-pipelines/release.yml
  drafts: false

resources:
  repositories:
    - repository: 1ESPipelineTemplates
      type: git
      name: 1ESPipelineTemplates/1ESPipelineTemplates
      ref: refs/tags/release

variables:
  TeamName: sarif-tools
  ARTIFACT_NAME_TARBALL: tarball
  ARTIFACT_NAME_WHEEL: wheel

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals 1ESPT-Ubuntu22.04
      os: Linux
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - template: azure-pipelines/templates/build_stage.yml@self
