name: Release

variables:
  TeamName: "sarif-tools"
  architecture: "x64"
  ARTIFACT_NAME_TARBALL: "tarball"
  ARTIFACT_NAME_WHEEL: "wheel"

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals 1ESPT-Ubuntu22.04
      os: Linux
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: Build
        jobs:
        - job: Build

          templateContext:
            outputs:
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)/wheel/sarif_tools-$(releaseVersion)-py3-none-any.whl
                sbomBuildDropPath: $(Build.ArtifactStagingDirectory)/wheel
                artifactName: $(ARTIFACT_NAME_WHEEL)
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)/tarball/sarif_tools-$(releaseVersion).tar.gz
                sbomBuildDropPath: $(Build.ArtifactStagingDirectory)/tarball
                artifactName: $(ARTIFACT_NAME_TARBALL)

          variables:
            python.version: "3.8"

          steps:
            - template: azure-pipelines/templates/use_python.yml@self

            - script: pipx install poetry
              displayName: Install Poetry

            - script: poetry build
              displayName: poetry build

            - powershell: |
                $releaseVersion = & poetry version --short
                echo "releaseVersion: $releaseVersion"
                echo "##vso[task.setvariable variable=releaseVersion]$releaseVersion"
              displayName: Get release version
              name: getReleaseVersionStep

            - script: pwd & ls -R
              displayName: List files

            - task: CopyFiles@2
              displayName: Copy wheel
              inputs:
                SourceFolder: dist
                Contents: sarif_tools-$(releaseVersion)-py3-none-any.whl
                TargetFolder: $(Build.ArtifactStagingDirectory)/wheel

            - task: CopyFiles@2
              displayName: Copy tarball
              inputs:
                SourceFolder: dist
                Contents: sarif_tools-$(releaseVersion).tar.gz
                TargetFolder: $(Build.ArtifactStagingDirectory)/tarball

      - stage: CreateRelease
        dependsOn:
          - Build
        variables:
          releaseVersion: $[ stageDependencies.Build.Build.outputs['getReleaseVersionStep.releaseVersion'] ]
        jobs:
        - job: CreateRelease
          steps:
            - task: GitHubRelease@1 #https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines
              displayName: Create GitHub Release
              inputs:
                gitHubConnection: GitHub-sarif-tools
                repositoryName: microsoft/sarif-tools
                action: create
                target: $(releaseVersion)
                isDraft: false
                addChangeLog: false
                tagSource: auto
                title: $(customTagName)
                assets: $(Pipeline.Workspace)/dist/*

      - stage: WaitForValidation
        dependsOn:
          - Build
        jobs:
          - job: wait_for_validation
            displayName: Wait for manual validation
            pool: server
            steps:
              - task: ManualValidation@0
                timeoutInMinutes: 1440 # task times out in 1 day
                inputs:
                  notifyUsers: 'erikd@microsoft.com'
                  instructions: 'Please test the latest draft release and then publish it.'
                  onTimeout: 'reject'
