name: Release
trigger: none
pr: none

variables:
  TeamName: sarif-tools
  architecture: x64
  ARTIFACT_NAME_TARBALL: tarball
  ARTIFACT_NAME_WHEEL: wheel

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals 1ESPT-Ubuntu22.04
      os: Linux
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: Build
        jobs:
        - job: Build

          templateContext:
            outputs:
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)/wheel/sarif_tools-$(releaseVersion)-py3-none-any.whl
                sbomBuildDropPath: $(Build.ArtifactStagingDirectory)/wheel
                artifactName: $(ARTIFACT_NAME_WHEEL)
              - output: pipelineArtifact
                targetPath: $(Build.ArtifactStagingDirectory)/tarball/sarif_tools-$(releaseVersion).tar.gz
                sbomBuildDropPath: $(Build.ArtifactStagingDirectory)/tarball
                artifactName: $(ARTIFACT_NAME_TARBALL)

          variables:
            python.version: "3.8"

          steps:
            - template: azure-pipelines/templates/use_python.yml@self

            - script: pipx install poetry
              displayName: Install Poetry

            - script: poetry build --no-interaction
              displayName: poetry build

            - powershell: |
                $releaseVersion = & poetry version --short
                echo "releaseVersion: $releaseVersion"
                echo "##vso[task.setvariable variable=releaseVersion]$releaseVersion"
                echo "##vso[task.setvariable variable=releaseVersionWithPrefix;isOutput=true]v$releaseVersion"
              displayName: Get release version
              name: getReleaseVersionStep

            - task: CopyFiles@2
              displayName: Copy wheel
              inputs:
                SourceFolder: dist
                Contents: sarif_tools-$(releaseVersion)-py3-none-any.whl
                TargetFolder: $(Build.ArtifactStagingDirectory)/wheel

            - task: CopyFiles@2
              displayName: Copy tarball
              inputs:
                SourceFolder: dist
                Contents: sarif_tools-$(releaseVersion).tar.gz
                TargetFolder: $(Build.ArtifactStagingDirectory)/tarball

      - stage: CreateRelease
        displayName: Create GitHub Release
        dependsOn: Build
        variables:
          releaseVersionWithPrefix: $[ stageDependencies.Build.Build.outputs['getReleaseVersionStep.releaseVersionWithPrefix'] ]
        jobs:
        - job: CreateRelease
          steps:
            - checkout: self
              fetchDepth: 1
              fetchTags: false
              persistCredentials: true

            - script: |
                git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config user.name "Azure Piplines"
                git fetch --depth 1 origin main
                git tag -a $(releaseVersionWithPrefix) -m "Release $(releaseVersionWithPrefix)" origin/main
                git push origin $(releaseVersionWithPrefix)
              displayName: Create git tag

            - task: GitHubRelease@1 #https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines
              displayName: Create GitHub Release
              inputs:
                gitHubConnection: GitHub-sarif-tools
                repositoryName: debonte/sarif-tools
                action: create
                target: $(releaseVersionWithPrefix)
                isDraft: true
                addChangeLog: false
                tagSource: auto
                title: $(customTagName)
                assets: $(Pipeline.Workspace)/dist/*

      - stage: WaitForValidation
        dependsOn: CreateRelease
        jobs:
          - job: wait_for_validation
            displayName: Wait for manual validation
            pool: server
            steps:
              - task: ManualValidation@0
                timeoutInMinutes: 1440 # task times out in 1 day
                inputs:
                  notifyUsers: 'erikd@microsoft.com'
                  instructions: 'Please test the latest draft release and then publish it.'
                  onTimeout: 'reject'

      - stage: Release
        dependsOn: WaitForValidation
        jobs:
        - job: Release
          displayName: Release to PyPi

          pool:
            name: VSEngSS-MicroBuild2022-1ES # This pool is required to have the certs needed to publish to PyPi using ESRP.
            os: windows
            image: server2022-microbuildVS2022-1es

          steps:
            - checkout: self

            - template: azure-pipelines/download_build_artifacts.yml@self
              parameters:
                buildId: ${{ parameters.buildId }}

            # Remove the _manifest folder (sbom) from the dist.signed artifact, since we don't want to publish it to PyPi
            - script: rd /s /q $(System.ArtifactsDirectory)\dist.signed\_manifest
              displayName: Remove _manifest folder

            # publish the signed package to PyPi
            - template: MicroBuild.Publish.yml@MicroBuildTemplate
              parameters:
                intent: PackageDistribution
                contentType: PyPi
                contentSource: Folder
                folderLocation: $(System.ArtifactsDirectory)/dist.signed
                waitForReleaseCompletion: true
                owners: erikd@microsoft.com
                approvers: grwheele@microsoft.com
