name: Release

variables:
  TeamName: "sarif-tools"
  architecture: "x64"
  ARTIFACT_NAME_TARBALL: "tarball"
  ARTIFACT_NAME_WHEEL: "wheel"

resources:
  repositories:
    - repository: MicroBuildTemplate
      type: git
      name: 1ESPipelineTemplates/MicroBuildTemplate
      ref: refs/tags/release

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    sdl:
      sourceAnalysisPool: VSEngSS-MicroBuild2022-1ES
    pool:
      name: AzurePipelines-EO
      demands:
        - ImageOverride -equals 1ESPT-Ubuntu22.04
      os: Linux
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: Build
        jobs:
        - job: Build

          templateContext:
            outputs:
              - output: pipelineArtifact
                targetPath: '$(Build.ArtifactStagingDirectory)/dist/*.whl'
                artifactName: $(ARTIFACT_NAME_WHEEL)
              - output: pipelineArtifact
                targetPath: '$(Build.ArtifactStagingDirectory)/dist/*.tar.gz'
                artifactName: $(ARTIFACT_NAME_TARBALL)

          variables:
            python.version: "3.8"

          steps:
            - template: azure-pipelines/templates/use_python.yml@self

            - script: pipx install poetry
              displayName: "Install Poetry"

            - script: poetry build
              displayName: "poetry build"

      # - stage: Create Release
      #   dependsOn:
      #     - Build
      #   jobs:
      #   - job: CreateRelease

      #     steps:
      #       - task: GitHubRelease@1 #https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/github-release-v1?view=azure-pipelines
      #         displayName: 'Create GitHub Release'
      #         inputs:
      #           gitHubConnection: 'GitHub-sarif-tools'
      #           repositoryName: 'microsoft/sarif-tools'
      #           action: 'create'
      #           target: '$(Build.SourceVersion)'
      #           isDraft: false
      #           addChangeLog: false
      #           tagSource: 'auto'
      #           title: '$(customTagName)'
      #           assets: |
      #             $(Pipeline.Workspace)/dist/*
