jobs:
  - job: Sign
    displayName: Sign wheel
    templateContext:
      outputs:
      - output: pipelineArtifact
        displayName: Publish signed artifacts
        artifactName: dist.signed
        targetPath: $(Build.StagingDirectory)/dist.signed

    pool:
      name: VSEngSS-MicroBuild2022-1ES
      # demands:
      #   - msbuild
      #   - npm

    steps:
      - task: MicroBuildSigningPlugin@4
        displayName: Install MicroBuild signing plugin
        inputs:
          signType: $(SIGN_TYPE)

      - task: NuGetToolInstaller@1
        displayName: Install NuGet

      - task: NuGetAuthenticate@1
        displayName: Authenticate NuGet for CFS package feed

      - task: PipAuthenticate@1.206.0
        displayName: Authenticate pip for CFS package feed
        inputs:
          artifactFeeds: DevDiv/debugpy

      - task: NuGetCommand@2
        displayName: Restore NuGet packages
        inputs:
          feedsToUse: config
          config: nuget.config
          restoreSolution: packages.config
          restoreDirectory: $(Build.BinariesDirectory)\packages

      - script: |
          echo ##vso[task.prependpath]$(Build.BinariesDirectory)\packages\python.3.8.0\tools
        displayName: Use Python version

      - download: current
        artifact: dist
        displayName: Download unsigned artifacts

      - script: python $(Build.SourcesDirectory)\wheels.py unpack
        displayName: Unpack wheel

      - task: MSBuild@1
        displayName: Sign binaries
        inputs:
          solution: $(Build.SourcesDirectory)\sign.proj

      - script: python $(Build.SourcesDirectory)\wheels.py rehash
        displayName: Rehash wheel

      - script: python $(Build.SourcesDirectory)\wheels.py repack
        displayName: Repack wheel

